sjtusite/comments/urls.py
from django.urls import path

from . import views

app_name = 'comments'
urlpatterns = [
    path('comment/<int:shop_pk>', views.comment, name='comment'),
]

sjtusite/shop/urls.py
from django.urls import path
from . import views

# http://localhost:8000
# http://localhost:8000/type/1
# http://localhost:8000/type/shop/1
# http://localhost:8000/1/1
# 

# start with shop
app_name = 'shop'  # 新添，在html页面中URL路径中都要加上"shop:"
urlpatterns = [
    # http://localhost:8000/shop/1
    path('', views.shop_list, name='shop_list'),
    #path('<int:shop_pk>', views.shop_detail, name='shop_detail'),
    path('shops/<int:shop_pk>/', views.shop_detail, name='shop_detail'),
    path('type/<int:shop_type_pk>', views.shop_with_type, name='shop_with_type'),
    path('search/', views.shop_search, name='shop_search'),
]

sjtusite/sjtusite/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name="comments"
urlpatterns = [
    path('', views.home, name='home'),
    path('admin/', admin.site.urls),
    path('shop/', include('shop.urls')),
    path('comment/', include('comments.urls')),
    path('', include('shop.urls')),
    path('', include('comments.urls')),
]

sjtusite/comments/models.py
from django.db import models
from django.utils import timezone
# Create your models here.


class Comment(models.Model):
    name = models.CharField('名字', max_length=50)
    text = models.TextField('内容')
    created_time = models.DateTimeField('创建时间', default=timezone.now)
    shop = models.ForeignKey('shop.Shop', null=True, verbose_name='店铺', on_delete=models.DO_NOTHING)

    class Meta:
        verbose_name = '评论'
        verbose_name_plural = verbose_name

    def __str__(self):
        return '{}: {}'.format(self.name, self.text[:20])

sjtusite/shop/models.py
from django.db import models

# Create your models here.
from django.urls import reverse
from django.utils import timezone


class ShopType(models.Model):
    type_name = models.CharField(max_length=10) # 吃的、喝的、玩的、学习、生活、打扮

    def __str__(self):
        return self.type_name

class Shop(models.Model):
    name = models.CharField(max_length=20)
    shop_type = models.ForeignKey(ShopType, on_delete=models.DO_NOTHING)
    content = models.TextField()

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):#新增
        self.modified_time = timezone.now()
        super().save(*args, **kwargs)

    def get_absolute_url(self):#新增
        return reverse('shop:shop_detail', kwargs={'shop_pk': self.pk})  #comment.view中重定向到 post 的详情页，当 redirect 函数接收一个模型的实例时调用这个模型实例的 get_absolute_url 方法

sjtusite/comments/forms.py
from django import forms
from .models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['name', 'text']

sjtusite/shop/forms.py
from django import forms


class SearchForm(forms.Form):
    query = forms.CharField()

sjtusite/comments/views.py
from django.contrib import messages
from django.shortcuts import render
from shop.models import Shop
from django.shortcuts import get_object_or_404, redirect, render
from django.views.decorators.http import require_POST
# Create your views here.

from .forms import CommentForm


@require_POST
def comment(request, shop_pk):
    shop = get_object_or_404(Shop, pk=shop_pk)
    form = CommentForm(request.POST)

    if form.is_valid():
        comment = form.save(commit=False)
        comment.shop = shop
        comment.save()

        messages.add_message(request, messages.SUCCESS, '评论发表成功！', extra_tags='success')

        return redirect(shop)
    context = {
        'shop': shop,
        'form': form,
    }
    messages.add_message(request, messages.ERROR, '评论发表失败！请修改表单中的错误后重新提交。', extra_tags='danger')

    return render(request, 'comments/preview.html', context=context)

sjtusite/shop/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Shop, ShopType
from django.contrib.postgres.search import SearchVector
from .forms import  SearchForm
from django.contrib.postgres.search import TrigramSimilarity

# Create your views here.
def shop_list(request):
    context = {}
    context['shops'] = Shop.objects.all()
    context['shop_types'] = ShopType.objects.all()
    return render(request, 'shop/shop_list.html', context)


def shop_detail(request, shop_pk):
     context = {}
     context['shop'] = get_object_or_404(Shop, pk=shop_pk)
     return render(request, 'shop/shop_detail.html', context)



def shop_with_type(request, shop_type_pk):
    context = {}
    shop_type = get_object_or_404(ShopType, pk=shop_type_pk)
    context['shops'] = Shop.objects.filter(shop_type=shop_type)
    context['shop_type'] = shop_type
    context['shop_types'] = ShopType.objects.all()
    return render(request, 'shop/shops_with_type.html', context)


#新增全文搜索功能，搜索范围是标题和简介
def shop_search(request):
    form = SearchForm()
    query = None
    results = []
    if 'query' in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            #search_vector = SearchVector('shop_name', 'detail')
            #目前只能完成根据精确匹配项计算出来的分数筛选出的项，
            #商店名的三元匹配已实现
            results= Shop.objects.annotate(
                                            similarity=TrigramSimilarity('name', query)*5+TrigramSimilarity('content', query),
                                            ).filter(similarity__gte=0.05).order_by('-similarity')
    context={   'query': query, 
                "form": form, 
                'results': results,
            }
    return render(request, 'shop/search.html', context
                                                      )

sjtusite/sjtusite/views.py
from django.shortcuts import render

def home(request):
    context = {}
    return render(request, 'home.html', context)

sjtusite/shop/templates/shop/search.html
<!---还没有具体地渲染--->
{% extends 'base.html' %}

{% block title %}
Search
{% endblock %}

{% block content %}

    {% if query %}<!--如果query有值，则进行查询-->
        <h1>包含关键词{{ query }}的店铺</h1>
            <h3><!!>
            {% with results.count as total_results %}
                Found {{ total_results }} result{{ total_results|pluralize }}
            {% endwith %}
            </h3>

        <!--循环显示查询结果，并生成对应结果标题的超链接-->
        {% for shop in results %}
            <h4>
                <a href="{{ shop.get_absolute_url }}">{{ shop.name}}</a>
            </h4>
            {{ shop.content|truncatewords:5 }}
        {% empty %}
            <p>There are no results for your query.</p>
        {% endfor %}

        <!重新查询的链接!>
        <p><a href="{% url 'shop:shop_search' %}">Search again</a></p>

    {% else %}<!--还没有提交表单前的表单页面-->
        <h1>Search for shops</h1>

        <form action="." method="get">
        {{ form.as_p }}<!此处会由form模板生成表单的界面!>
            <!以下会生成一个提交按钮!>
            <input type="submit" value="搜索">
        </form>
    {% endif %}

{% endblock %}

sjtusite/shop/templates/shop/shop_detail.html
{% extends 'base.html' %}
{% load comments_extras %}

{% block title %}
    {{ shop.name }}
{% endblock %}

{% block 'nav_shop_active' %}active{% endblock %}

{% load static  %}
{% block header_extends %}
    <link rel="stylesheet" href="{% static 'shop/shop.css' %}">
{% endblock %}

{% block content %}

    {% if messages %}
    {% for message in messages %}
      <div class="alert alert-{{ message.tags }} alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
                aria-hidden="true">&times;</span></button>
        {{ message }}
      </div>
    {% endfor %}
{% endif %}


    <div class="container">
        <div class="row">  
            <div class="col-xs-10 col-xs-offset-1">
                <h3>{{ shop.name }}</h3>
                <ul class="shop-info-description">
                    <li>分类： 
                        <a href="{% url 'shop:shop_with_type' shop.shop_type.pk %}">
                            {{ shop.shop_type }}
                        </a>
                    </li>
                </ul>   
                <div class="shop-content">{{ shop.content|linebreaksbr }}</div>
            </div>
        </div>
    </div>
    <!--section class="comment-area" id="comment-area">#新增评论区模块-->
    <hr>
      <h3>发表评论</h3>
    {% show_comment_form shop %}
    <div class="comment-list-panel">
    {% show_comments shop %}
</div>
    </section>

{% endblock %} 

sjtusite/shop/templates/shop/shop_list.html
{% extends 'base.html' %}

{% block title %}交大优铺{% endblock %}

{% block 'nav_shop_active' %}active{% endblock %}

{% load static  %}
{% block header_extends %}
    <link rel="stylesheet" href="{% static 'shop/shop.css' %}">
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-sm-8 col-md-8">
                <div class="panel panel-default">
                    <div class="panel-heading">{% block shop_list_title %}店铺列表（一共有{{ shops|length }}个店铺）{% endblock %}</div>
                    <div class="panel-body">
                         {% for shop in shops %}
                            <div class="shop">
                                <h3><a href="{% url 'shop:shop_detail' shop.pk %}">{{ shop.name }}</a></h3>
                                <p class="shop-info">
                                    <span class="glyphicon glyphicon-tag"></span><a href="{% url 'shop:shop_with_type' shop.shop_type.pk %}">{{ shop.shop_type }}</a>
                                </p>
                                <p>{{ shop.content|truncatechars:50|linebreaksbr }}</p>
                            </div>
                        {% endfor %}
                    </div>
                </div>
               
            </div>
            <div class="col-sm-4 col-md-4">
                <div class="panel panel-default">
                  <div class="panel-heading">店铺分类</div>
                  <div class="panel-body">
                    <ul class="shop-types">
                        {% for shop_type in shop_types %}
                            <li><a href="{% url 'shop:shop_with_type' shop_type.pk %}">{{ shop_type.type_name }}</a></li>
                        {% endfor %}
                    </ul>
                  </div>
                </div>
            </div>
        </div>
    </div>


{% endblock %}

sjtusite/shop/templates/shop/shops_with_type.html
{% extends 'shop/shop_list.html' %}

{% block title %}
    {{ shop_type.type_name }}
{% endblock %}

{% block shop_list_title %}
    分类：{{ shop_type.type_name }}
    <a href="{% url 'shop:shop_list' %}">查看全部店铺</a>
{% endblock %}

sjtusite/shop/templates/type_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>交大优铺</title>
</head>
<body>
    <ul>
        {% for type in types %}
            <li>
                <a href="{{type.type_name}}">
                    {{type.type_name1}}
                </a>
            </li>
        {% endfor %}
    </ul>
</body>
</html>

sjtusite/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'base.css' %}">
    <link rel="stylesheet" href="{% static 'bootstrap-3.3.7/css/bootstrap.min.css' %}">
    <script type="text/javascript" src="{% static 'jquery.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'bootstrap-3.3.7/js/bootstrap.min.js' %}"></script>
    {% block header_extends %}{% endblock %}
</head>
<body>
    <div class="navbar navbar-default navbar-fixed-top" role="navigation">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand" href="{% url 'home' %}">交大优铺</a>
                <button class="navbar-toggle collaps" data-toggle="collapse" data-target="#navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div id="navbar-collapse" class="collapse navbar-collapse" >
                <ul class="nav navbar-nav">
                    <li class="{% block nav_home_active %}{% endblock %}"><a href="{% url 'home' %}">首页</a>
                    </li>
                    <li class="{% block nav_shop_active %}{% endblock %}"><a href="{% url 'shop:shop_list' %}">店铺</a>
                    </li>
                    <li class="{% block nav_search_active %}{% endblock %}"><a href="{% url 'shop:shop_search' %}">搜索</a>
                    </li>
                </ul>
            </div>      
        </div>
    </div>
    {% block content %}{% endblock %}
</body>
</html>

sjtusite/templates/comments/inclusions/_form.html
<form action="{% url 'comments:comment' shop.pk %}" method="post" class="comment-form">
  {% csrf_token %}
  <div class="row">
    <div class="col-md-4">
      <label for="{{ form.name.id_for_label }}">{{ form.name.label }}：</label>
      {{ form.name }}
      {{ form.name.errors }}
    </div>

    <div class="col-md-12">
      <label for="{{ form.text.id_for_label }}">{{ form.text.label }}：</label>
      {{ form.text }}
      {{ form.text.errors }}
      <button type="submit" class="comment-btn">发表</button>
    </div>
  </div>    <!-- row -->
</form>

sjtusite/templates/comments/inclusions/_list.html
<h3>评论列表，共 <span>{{ comment_count }}</span> 条评论</h3>
<ul class="comment-list list-unstyled">
  {% for comment in comment_list %}
    <li class="comment-item">
      <span class="nickname">{{ comment.name }}</span>
      <time class="submit-date" datetime="{{ comment.created_time }}">{{ comment.created_time }}</time>
      <div class="text">
        {{ comment.text|linebreaks }}
      </div>
    </li>
  {% empty %}
    暂无评论
  {% endfor %}
</ul>

sjtusite/templates/comments/preview.html
{% extends 'base.html' %}
{% load comments_extras %}
 
{% block main %}
  {% show_comment_form shop form %}
{% endblock main %}

sjtusite/templates/home.html
{% extends 'base.html' %}
{% load static  %}

{% block title %}
    交大优铺|首页
{% endblock %}

{% block header_extends %}
    <link rel="stylesheet" href="{% static 'home.css' %}">
{% endblock %}

{% block nav_home_active %}active{% endblock %}

{% block content %}
    <<div class="container-fluid">
	<div class="row-fluid">
		<div class="col-xs-4">
			<div class="hero-unit well">
				<h2>
					吃的!
				</h2>
				<p>
					好吃的东西.
				</p>
				<p>
					<a class="btn btn-primary btn-large" href="{% url 'shop:shop_with_type' 1 %}">更多 »</a>
				</p>
			</div>
		</div>
		<div class="col-xs-4">
			<div class="hero-unit well">
				<h2>
					喝的!
				</h2>
				<p>
					好喝的东西.
				</p>
				<p>
					<a class="btn btn-primary btn-large" href="{% url 'shop:shop_with_type' 2 %}">更多 »</a>
				</p>
			</div>
		</div>
		<div class="col-xs-4">
			<div class="hero-unit well">
				<h2>
					玩的!
				</h2>
				<p>
					好玩的东西.
				</p>
				<p>
					<a class="btn btn-primary btn-large" href="{% url 'shop:shop_with_type' 3 %}">更多 »</a>
				</p>
			</div>
		</div>
	</div>
	<div class="row-fluid">
		<div class="col-xs-4">
			<div class="hero-unit well">
				<h2>
					学习!
				</h2>
				<p>
					学在交大.
				</p>
				<p>
					<a class="btn btn-primary btn-large" href="{% url 'shop:shop_with_type' 4 %}">更多 »</a>
				</p>
			</div>
		</div>
		<div class="col-xs-4">
			<div class="hero-unit well">
				<h2>
					生活!
				</h2>
				<p>
					便捷生活.
				</p>
				<p>
					<a class="btn btn-primary btn-large" href="{% url 'shop:shop_with_type' 5 %}">更多 »</a>
				</p>
			</div>
		</div>
		<div class="col-xs-4">
			<div class="hero-unit well">
				<h2>
					打扮!
				</h2>
				<p>
					打扮自己.
				</p>
				<p>
					<a class="btn btn-primary btn-large" href="{% url 'shop:shop_with_type' 6 %}">更多 »</a>
				</p>
			</div>
		</div>
	</div>
</div>
{% endblock %}